"""initial models

Revision ID: 0bd11b7d9f87
Revises: 
Create Date: 2026-04-04 12:43:13.285673

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0bd11b7d9f87'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('tg_id', sa.BigInteger(), nullable=False),
    sa.Column('username', sa.String(length=64), server_default='', nullable=False),
    sa.Column('bio_coins', sa.Integer(), server_default='0', nullable=False),
    sa.Column('premium_coins', sa.Integer(), server_default='0', nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('last_active', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('tg_id')
    )
    op.create_index(op.f('ix_users_tg_id'), 'users', ['tg_id'], unique=False)
    op.create_table('immunities',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('owner_id', sa.BigInteger(), nullable=False),
    sa.Column('level', sa.Integer(), server_default='1', nullable=False),
    sa.Column('resistance', sa.Integer(), server_default='10', nullable=False),
    sa.Column('detection_power', sa.Float(), server_default='0.1', nullable=False),
    sa.Column('recovery_speed', sa.Float(), server_default='0.1', nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['users.tg_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_immunities_owner_id'), 'immunities', ['owner_id'], unique=True)
    op.create_table('infections',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('attacker_id', sa.BigInteger(), nullable=False),
    sa.Column('victim_id', sa.BigInteger(), nullable=False),
    sa.Column('started_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('damage_per_tick', sa.Float(), server_default='1.0', nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default='1', nullable=False),
    sa.ForeignKeyConstraint(['attacker_id'], ['users.tg_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['victim_id'], ['users.tg_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_infections_attacker_id'), 'infections', ['attacker_id'], unique=False)
    op.create_index(op.f('ix_infections_victim_id'), 'infections', ['victim_id'], unique=False)
    op.create_table('resource_transactions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('amount', sa.Integer(), nullable=False),
    sa.Column('currency', sa.Enum('BIO_COINS', 'PREMIUM_COINS', name='currency'), nullable=False),
    sa.Column('reason', sa.Enum('MINING', 'INFECTION_INCOME', 'INFECTION_LOSS', 'UPGRADE', 'DONATION', 'DAILY_BONUS', name='transactionreason'), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.tg_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_resource_transactions_user_id'), 'resource_transactions', ['user_id'], unique=False)
    op.create_table('viruses',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('owner_id', sa.BigInteger(), nullable=False),
    sa.Column('name', sa.String(length=64), server_default='Unnamed Virus', nullable=False),
    sa.Column('level', sa.Integer(), server_default='1', nullable=False),
    sa.Column('attack_power', sa.Integer(), server_default='10', nullable=False),
    sa.Column('spread_rate', sa.Float(), server_default='0.1', nullable=False),
    sa.Column('mutation_points', sa.Integer(), server_default='0', nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['users.tg_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_viruses_owner_id'), 'viruses', ['owner_id'], unique=True)
    op.create_table('immunity_upgrades',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('immunity_id', sa.Integer(), nullable=False),
    sa.Column('branch', sa.Enum('BARRIER', 'DETECTION', 'REGENERATION', name='immunitybranch'), nullable=False),
    sa.Column('level', sa.Integer(), server_default='1', nullable=False),
    sa.Column('effect_value', sa.Float(), server_default='0.0', nullable=False),
    sa.ForeignKeyConstraint(['immunity_id'], ['immunities.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_immunity_upgrades_immunity_id'), 'immunity_upgrades', ['immunity_id'], unique=False)
    op.create_table('virus_upgrades',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('virus_id', sa.Integer(), nullable=False),
    sa.Column('branch', sa.Enum('LETHALITY', 'CONTAGION', 'STEALTH', name='virusbranch'), nullable=False),
    sa.Column('level', sa.Integer(), server_default='1', nullable=False),
    sa.Column('effect_value', sa.Float(), server_default='0.0', nullable=False),
    sa.ForeignKeyConstraint(['virus_id'], ['viruses.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_virus_upgrades_virus_id'), 'virus_upgrades', ['virus_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_virus_upgrades_virus_id'), table_name='virus_upgrades')
    op.drop_table('virus_upgrades')
    op.drop_index(op.f('ix_immunity_upgrades_immunity_id'), table_name='immunity_upgrades')
    op.drop_table('immunity_upgrades')
    op.drop_index(op.f('ix_viruses_owner_id'), table_name='viruses')
    op.drop_table('viruses')
    op.drop_index(op.f('ix_resource_transactions_user_id'), table_name='resource_transactions')
    op.drop_table('resource_transactions')
    op.drop_index(op.f('ix_infections_victim_id'), table_name='infections')
    op.drop_index(op.f('ix_infections_attacker_id'), table_name='infections')
    op.drop_table('infections')
    op.drop_index(op.f('ix_immunities_owner_id'), table_name='immunities')
    op.drop_table('immunities')
    op.drop_index(op.f('ix_users_tg_id'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
