"""add_notification_settings_to_users

Revision ID: 116505ac4465
Revises: c1d2e3f4a5b6
Create Date: 2026-04-04 22:56:48.604338

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '116505ac4465'
down_revision: Union[str, None] = 'c1d2e3f4a5b6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('market_listings', 'listing_type',
               existing_type=sa.VARCHAR(length=12),
               type_=sa.Enum('SELL_ITEM', 'SELL_MUTATION', 'HIT_CONTRACT', 'SELL_COINS', 'BUY_COINS', name='listingtype'),
               existing_nullable=False)
    op.create_foreign_key(None, 'market_listings', 'items', ['item_id'], ['id'])
    op.create_foreign_key(None, 'market_listings', 'mutations', ['mutation_id'], ['id'])
    op.create_unique_constraint('uq_referral_rewards_user_level', 'referral_rewards', ['user_id', 'level'])
    op.alter_column('resource_transactions', 'reason',
               existing_type=sa.VARCHAR(length=16),
               type_=sa.Enum('MINING', 'INFECTION_INCOME', 'INFECTION_LOSS', 'UPGRADE', 'DONATION', 'DAILY_BONUS', 'TRANSFER_OUT', 'TRANSFER_IN', 'ALLIANCE_DONATION', 'REFERRAL_REWARD', name='transactionreason'),
               existing_nullable=False)
    op.add_column('users', sa.Column('notify_attacks', sa.Boolean(), server_default='1', nullable=False))
    op.add_column('users', sa.Column('notify_infections', sa.Boolean(), server_default='1', nullable=False))
    op.add_column('users', sa.Column('notify_cooldowns', sa.Boolean(), server_default='0', nullable=False))
    op.add_column('users', sa.Column('notify_events', sa.Boolean(), server_default='1', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'notify_events')
    op.drop_column('users', 'notify_cooldowns')
    op.drop_column('users', 'notify_infections')
    op.drop_column('users', 'notify_attacks')
    op.alter_column('resource_transactions', 'reason',
               existing_type=sa.Enum('MINING', 'INFECTION_INCOME', 'INFECTION_LOSS', 'UPGRADE', 'DONATION', 'DAILY_BONUS', 'TRANSFER_OUT', 'TRANSFER_IN', 'ALLIANCE_DONATION', 'REFERRAL_REWARD', name='transactionreason'),
               type_=sa.VARCHAR(length=16),
               existing_nullable=False)
    op.drop_constraint('uq_referral_rewards_user_level', 'referral_rewards', type_='unique')
    op.drop_constraint(None, 'market_listings', type_='foreignkey')
    op.drop_constraint(None, 'market_listings', type_='foreignkey')
    op.alter_column('market_listings', 'listing_type',
               existing_type=sa.Enum('SELL_ITEM', 'SELL_MUTATION', 'HIT_CONTRACT', 'SELL_COINS', 'BUY_COINS', name='listingtype'),
               type_=sa.VARCHAR(length=12),
               existing_nullable=False)
    # ### end Alembic commands ###
