"""add_items_table

Revision ID: 6a3a077c0b01
Revises: 7bc3394f9191
Create Date: 2026-04-04 15:57:57.856385

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6a3a077c0b01'
down_revision: Union[str, None] = '7bc3394f9191'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('events',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('event_type', sa.Enum('PANDEMIC', 'GOLD_RUSH', 'ARMS_RACE', 'PLAGUE_SEASON', 'IMMUNITY_WAVE', 'MUTATION_STORM', 'CEASEFIRE', name='eventtype'), nullable=False),
    sa.Column('title', sa.String(length=64), nullable=False),
    sa.Column('description', sa.String(length=512), server_default='', nullable=False),
    sa.Column('started_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('ends_at', sa.DateTime(), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default='1', nullable=False),
    sa.Column('created_by', sa.BigInteger(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('items',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('owner_id', sa.BigInteger(), nullable=False),
    sa.Column('item_type', sa.Enum('VACCINE', 'SHIELD_BOOST', 'ANTIDOTE', 'BIO_BOMB', 'VIRUS_ENHANCER', 'STEALTH_CLOAK', 'RESOURCE_BOOSTER', 'LUCKY_CHARM', 'SPY_DRONE', 'MUTATION_SERUM', name='itemtype'), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('used_at', sa.DateTime(), nullable=True),
    sa.Column('is_used', sa.Boolean(), server_default='0', nullable=False),
    sa.Column('effect_expires_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['owner_id'], ['users.tg_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_items_owner_id'), 'items', ['owner_id'], unique=False)
    op.create_table('market_listings',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('seller_id', sa.BigInteger(), nullable=False),
    sa.Column('listing_type', sa.Enum('SELL_COINS', 'BUY_COINS', 'HIT_CONTRACT', name='listingtype'), nullable=False),
    sa.Column('status', sa.Enum('ACTIVE', 'COMPLETED', 'CANCELLED', 'EXPIRED', name='listingstatus'), server_default='ACTIVE', nullable=False),
    sa.Column('amount', sa.Integer(), server_default='0', nullable=False),
    sa.Column('price', sa.Integer(), server_default='0', nullable=False),
    sa.Column('target_username', sa.String(length=64), nullable=True),
    sa.Column('target_id', sa.BigInteger(), nullable=True),
    sa.Column('reward', sa.Integer(), server_default='0', nullable=False),
    sa.Column('buyer_id', sa.BigInteger(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['buyer_id'], ['users.tg_id'], ),
    sa.ForeignKeyConstraint(['seller_id'], ['users.tg_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_market_listings_seller_id'), 'market_listings', ['seller_id'], unique=False)
    op.create_table('pandemic_participants',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('event_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('damage_dealt', sa.Integer(), server_default='0', nullable=False),
    sa.Column('last_attack_at', sa.DateTime(), nullable=True),
    sa.Column('joined_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.tg_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pandemic_participants_event_id'), 'pandemic_participants', ['event_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_pandemic_participants_event_id'), table_name='pandemic_participants')
    op.drop_table('pandemic_participants')
    op.drop_index(op.f('ix_market_listings_seller_id'), table_name='market_listings')
    op.drop_table('market_listings')
    op.drop_index(op.f('ix_items_owner_id'), table_name='items')
    op.drop_table('items')
    op.drop_table('events')
    # ### end Alembic commands ###
