"""add_repeatable_referral_claims_to_users

Revision ID: 6e4dfdb75465
Revises: 116505ac4465
Create Date: 2026-04-05 15:22:52.921962

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6e4dfdb75465'
down_revision: Union[str, None] = '116505ac4465'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('repeatable_referral_claims', sa.Integer(), server_default='0', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'repeatable_referral_claims')
    # ### end Alembic commands ###
