"""add attack_attempts

Revision ID: 75a9adbf2da0
Revises: ec3abb9cfc50
Create Date: 2026-04-04 16:33:14.010297

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '75a9adbf2da0'
down_revision: Union[str, None] = 'ec3abb9cfc50'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('attack_attempts',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('attacker_id', sa.BigInteger(), nullable=False),
    sa.Column('victim_id', sa.BigInteger(), nullable=False),
    sa.Column('success', sa.Boolean(), nullable=False),
    sa.Column('attempted_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['attacker_id'], ['users.tg_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['victim_id'], ['users.tg_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_attack_attempts_attacker_id'), 'attack_attempts', ['attacker_id'], unique=False)
    op.create_index(op.f('ix_attack_attempts_victim_id'), 'attack_attempts', ['victim_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_attack_attempts_victim_id'), table_name='attack_attempts')
    op.drop_index(op.f('ix_attack_attempts_attacker_id'), table_name='attack_attempts')
    op.drop_table('attack_attempts')
    # ### end Alembic commands ###
