"""add_premium_prefix_to_users

Revision ID: 78570e7702c9
Revises: 5a153f5f7531
Create Date: 2026-04-04 17:35:47.986231

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '78570e7702c9'
down_revision: Union[str, None] = '5a153f5f7531'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('alliances', sa.Column('alliance_coins', sa.Integer(), server_default='0', nullable=False))
    op.add_column('alliances', sa.Column('shield_level', sa.Integer(), server_default='0', nullable=False))
    op.add_column('alliances', sa.Column('morale_level', sa.Integer(), server_default='0', nullable=False))
    op.add_column('alliances', sa.Column('capacity_level', sa.Integer(), server_default='0', nullable=False))
    op.add_column('alliances', sa.Column('mining_level', sa.Integer(), server_default='0', nullable=False))
    op.add_column('alliances', sa.Column('regen_level', sa.Integer(), server_default='0', nullable=False))
    op.add_column('users', sa.Column('premium_prefix', sa.String(length=10), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'premium_prefix')
    op.drop_column('alliances', 'regen_level')
    op.drop_column('alliances', 'mining_level')
    op.drop_column('alliances', 'capacity_level')
    op.drop_column('alliances', 'morale_level')
    op.drop_column('alliances', 'shield_level')
    op.drop_column('alliances', 'alliance_coins')
    # ### end Alembic commands ###
