"""add alliances

Revision ID: 7bc3394f9191
Revises: d8cf4a073a4c
Create Date: 2026-04-04 15:46:11.753775

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7bc3394f9191'
down_revision: Union[str, None] = 'd8cf4a073a4c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('alliances',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=32), nullable=False),
    sa.Column('tag', sa.String(length=5), nullable=False),
    sa.Column('leader_id', sa.BigInteger(), nullable=False),
    sa.Column('description', sa.String(length=256), server_default='', nullable=False),
    sa.Column('max_members', sa.Integer(), server_default='20', nullable=False),
    sa.Column('defense_bonus', sa.Float(), server_default='0', nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['leader_id'], ['users.tg_id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name'),
    sa.UniqueConstraint('tag')
    )
    op.create_table('alliance_members',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('alliance_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('role', sa.Enum('LEADER', 'OFFICER', 'MEMBER', name='alliancerole'), nullable=False),
    sa.Column('joined_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['alliance_id'], ['alliances.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.tg_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_alliance_members_alliance_id'), 'alliance_members', ['alliance_id'], unique=False)
    op.create_index(op.f('ix_alliance_members_user_id'), 'alliance_members', ['user_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_alliance_members_user_id'), table_name='alliance_members')
    op.drop_index(op.f('ix_alliance_members_alliance_id'), table_name='alliance_members')
    op.drop_table('alliance_members')
    op.drop_table('alliances')
    # ### end Alembic commands ###
