"""add mutations

Revision ID: d8cf4a073a4c
Revises: 0bd11b7d9f87
Create Date: 2026-04-04 15:43:16.751365

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd8cf4a073a4c'
down_revision: Union[str, None] = '0bd11b7d9f87'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('mutations',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('owner_id', sa.BigInteger(), nullable=False),
    sa.Column('mutation_type', sa.Enum('TOXIC_SPIKE', 'RAPID_SPREAD', 'PHANTOM_STRAIN', 'RESOURCE_DRAIN', 'ADAPTIVE_SHELL', 'REGENERATIVE_CORE', 'DOUBLE_STRIKE', 'BIO_MAGNET', 'UNSTABLE_CODE', 'IMMUNE_LEAK', 'SLOW_REPLICATION', 'PLAGUE_BURST', 'ABSOLUTE_IMMUNITY', 'EVOLUTION_LEAP', name='mutationtype'), nullable=False),
    sa.Column('rarity', sa.Enum('COMMON', 'UNCOMMON', 'RARE', 'LEGENDARY', name='mutationrarity'), nullable=False),
    sa.Column('effect_value', sa.Float(), server_default='0.0', nullable=False),
    sa.Column('duration_hours', sa.Float(), server_default='4.0', nullable=False),
    sa.Column('activated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default='1', nullable=False),
    sa.Column('is_used', sa.Boolean(), server_default='0', nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['users.tg_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_mutations_owner_id'), 'mutations', ['owner_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_mutations_owner_id'), table_name='mutations')
    op.drop_table('mutations')
    # ### end Alembic commands ###
