"""add promo codes

Revision ID: ec3abb9cfc50
Revises: 56e4c4645859
Create Date: 2026-04-04 16:06:24.113125

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ec3abb9cfc50'
down_revision: Union[str, None] = '56e4c4645859'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('promo_codes',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('code', sa.String(length=32), nullable=False),
    sa.Column('bio_coins', sa.Integer(), server_default='0', nullable=False),
    sa.Column('premium_coins', sa.Integer(), server_default='0', nullable=False),
    sa.Column('max_activations', sa.Integer(), server_default='1', nullable=False),
    sa.Column('current_activations', sa.Integer(), server_default='0', nullable=False),
    sa.Column('created_by', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default='1', nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_promo_codes_code'), 'promo_codes', ['code'], unique=True)
    op.create_table('promo_activations',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('promo_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('activated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['promo_id'], ['promo_codes.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.tg_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('promo_id', 'user_id', name='uq_promo_user')
    )
    op.create_index(op.f('ix_promo_activations_promo_id'), 'promo_activations', ['promo_id'], unique=False)
    op.create_index(op.f('ix_promo_activations_user_id'), 'promo_activations', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_promo_activations_user_id'), table_name='promo_activations')
    op.drop_index(op.f('ix_promo_activations_promo_id'), table_name='promo_activations')
    op.drop_table('promo_activations')
    op.drop_index(op.f('ix_promo_codes_code'), table_name='promo_codes')
    op.drop_table('promo_codes')
    # ### end Alembic commands ###
