"""add name_entities_json to viruses

Revision ID: fefb12584025
Revises: 75a9adbf2da0
Create Date: 2026-04-04 16:44:51.199211

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fefb12584025'
down_revision: Union[str, None] = '75a9adbf2da0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('premium_until', sa.DateTime(), nullable=True))
    op.add_column('viruses', sa.Column('name_entities_json', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('viruses', 'name_entities_json')
    op.drop_column('users', 'premium_until')
    # ### end Alembic commands ###
